---

- hosts: servers_IP
  remote_user: root

  tasks:
  - name: Set Network Manager config file
    lineinfile:
      dest: /etc/NetworkManager/NetworkManager.conf
      regexp: '^dns=none'
      insertafter: '^\[main]'
      line: 'dns=none'
    notify: restart-NetworkManager

  roles:
    - ahuffman.resolv

# Handler to restart service
  handlers:
  - name: restart-NetworkManager
    systemd:
      name: NetworkManager
      state: restarted
      daemon_reload: yes
