---

- hosts: servers_IP
  remote_user: root

  vars_prompt:
    - name: "adminuser"
      prompt: "Enter AD Admin User Name"
      private: no
    - name: "ad_password"
      prompt: "Enter AD Domain User Password"
      private: yes

  tasks:
  - name: install software for join AD
    yum: pkg={{item}} state=installed disable_gpg_check=yes
    with_items:
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - sssd
      - samba-common-tools
      - python-pip

  - name: Check if pexpect installed
    shell: "pip list | grep pexpect"
    register: pip_installed
    changed_when: false
    ignore_errors: true

  - name: install pexpect using pip
    # remove proxy parameter if not need
    shell: "pip --proxy http://{{ proxyserver }}:{{ proxyport }} install pexpect"
    when: pip_installed|failed

  - name: Check if joined domain
    shell: "realm list | grep sssd"
    register: realm_bound
    changed_when: false
    ignore_errors: true

  - expect:
      command: "realm join {{ domainname }} --computer-ou={{ computerou }} --user={{ adminuser }}"
      responses:
        Password for .*: "{{ ad_password }}"
    when: realm_bound|failed

  - name: Change sssd.conf setting use_fully_qualified_names
    lineinfile:
      dest: /etc/sssd/sssd.conf
      regexp: '^use_fully_qualified_names'
      line: 'use_fully_qualified_names = False'
    notify:
      - restart sssd

  - name: Change sssd.conf setting fallback_homedir
    lineinfile:
      dest: /etc/sssd/sssd.conf
      regexp: '^fallback_homedir'
      line: 'fallback_homedir = /home/%d/%u'
    notify:
      - restart sssd

  - name: Change sssd.conf setting append ddns setting
    lineinfile:
      dest: /etc/sssd/sssd.conf
      line: '{{item}}'
    with_items:
      - dyndns_update = true
      - dyndns_refresh_interval = 43200
      - dyndns_update_ptr = true
      - dyndns_ttl = 3600
    notify:
      - restart sssd

  handlers:
    - name: restart sssd
      systemd: name=sssd state=restarted daemon_reload=yes
